# Generated by Django 3.2.13 on 2022-06-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descripcion',
            new_name='description',
        ),
    ]
